### ISSUE TITLE
Toggle PostScript Preview always showing "could not find `gs` installed".

### ISSUE THREAD

**Issue by santanuchakrabarti** [Alhadis/Atom-PostScript#2]
I have Ghostscript installed in my machine and PATH variable is appropriately set. From command line I am able to run Ghostscript and also gsview. But the Atom previewer is failing to find Ghostscript.

**Comment by Alhadis** [comment]
How are you running GhostScript from command-line? Are you sure that it's named `gs`?

Also, what OS are you using?

**Comment by santanuchakrabarti** [comment]
I am running in Window 10 machine and my Ghostscript executable file name is gswin64. I think there should be some configuration facility to mention the exe name, but I find none in the settings tab of the package.

**Comment by Alhadis** [comment]
Ah, that would explain it: I never bothered to test this package on Windows. 😅

I've updated [`exec-path.js`](https://github.com/Alhadis/Atom-PostScript/blob/bef9df9c349649f7657c822f22419f3a4fd01562/lib/exec-path.js) to use `gswin64` instead of `gs` on Windows systems. In addition, a new package setting will enable you to override the GhostScript executable's name if need be.

Let me know if you're still having troubles. 👍

**Comment by santanuchakrabarti** [comment]
Thanks for your speedy response. Hope you merged the changes to the master branch. Let me update the package and check this.
